
version: '3.8'

services:
  backend:
    build: ./backend
    expose:
      - "5000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    expose:
      - "80"
    depends_on:
      - backend

  db:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
